# .github/workflows/retrieve-secrets.yml
name: 1Password Secrets Retrieval

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment (defaults to dev)'
        required: false
        type: string
        default: 'dev'
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: '1Password Service Account token'
        required: true

jobs:
  retrieve-secrets:
    name: Retrieve Environment Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        run: |
          curl -sS https://downloads.1password.com/linux/debian/amd64/stable/1password-cli.deb -o 1password-cli.deb
          sudo apt install ./1password-cli.deb
          rm 1password-cli.deb

      - name: Retrieve secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/retrieve_secrets.sh
